language: cpp
dist: xenial
os:
- linux
env:
- CONFIG=Debug
before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -y
- sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev -y
- sudo apt-get install qt5-default qttools5-dev-tools -y
- sudo apt-get install clang -y
script:
- mkdir build
- cd build
- export CXX="clang++"
- export CC="clang"
- qmake ..
- make -j 3
- sha1sum tests > tests.sha1
- cd ..
notifications:
  email:
  - denisacostaq@gmail.com
deploy:
  provider: releases
  api_key:
    secure: UoRNKWjDcWJW4D+ij11EguI/opku0BkIi8nkBbrtw2LHvJapuucCCPyh3nWQJfNVe63SBVR+CSDlCtaRclszHE3UsQItjxJimy0S1E9g0KBBm3kIhWG9UODnfW0WYS3PvF8bSxWskQRQ8Czcdu4k1dER19OeNjm2z3jNRm77Y0JifadIOrGgm7EmDJgBSJgNRKxN1Ul2NZ2NJWBHq8cPz2QyIJ5eBcUpW6p2gIs2b7sWALkXq4PsMDlV1fFlGL/PMiOS6GIlgAFP0n58NFM4fzef0+kE44/tEz5yDHu/b6fbHhs1M4N9QPawwuu4E0TYdjT3MUQWd5wdVDROX83gGRq5ED6ORJXNLk7/Ss3deQMQwX06oT9hs3VKR95tZAFGiqHhd2KgOl/Q/dc/725bxUNiClc5lDQYdzXPClutj1dgiSnPApTJywxnfmwcNgpRx0Emb1NjTnJx/3z9Lb8v2BFx0B63e6t3RdHfp7CFLLqHdpNPPgkvR7zOPflPonEIeibC+hmQEigsBikjyQQAjJZSNshU+u+Qp2CcebS4Aeq4ophSa16mCRzWPwbkNGOYp3mrZSJzIgLST1nSd9X1xjk76FhxPaLtwsN/1QaUUmv2X6qmROwhnKg3+qVECjjdk8Yu8KKltJg4rhk4GULtLCh1ihnk1uBdzYFNs8g7qRI=
  file: 
   - build/tests
   - vuild/tests.sha1
  skip_cleanup: true
  draft: true
  on:
    repo: denisacostaq/ttt
    tags: true
